config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users
  resources :vehicles
  root "vehicles#index"
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :vehicles
  belongs_to :role

  canadian_postal_code = /\A[ABCEGHJKLMNPRSTVXY]{1}\d{1}[A-Z]{1}[ -]?\d{1}[A-Z]{1}\d{1}\z/
  validates :email, :uniqueness => true
  validates :fname, :lname, :street, :city, :postal, :phone, :presence => true
  validates :postal, :format => { :with => canadian_postal_code }
  validates :phone, :length => { :is => 10, :message => 'must only contain 10 digits.' }
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
	belongs_to :user

	validates :colour, format: { with: /[a-zA-Z]+/, message: 'Invalid. Only accept letters.' }
    validates :year, length: { is: 4, message: 'Invalid. Year must be 4 digits.'},
	    numericality: { greater_than_or_equal_to: 1900, 
	    	message: 'Invalid. Year must be greater than or equal to 1900.' }
	validates :license, :make, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :fname, :lname, :street, :city, :province, :postal, :phone)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :fname, :lname, :street, :city, :province, :postal, :phone)
  end
end 

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :fname, :lname, :street, :city, :province, :postal, :phone, :password, :password_confirmation, :role_id)
  end

  def account_update_params
    params.require(:user).permit(:email, :fname, :lname, :street, :city, :province, :postal, :phone, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @users = User.all 
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to @user
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :fname, :lname, :street, :city, :province, :postal, :phone)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
	before_action :find_vehicle, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!
  def index
  	@vehicles = Vehicle.all
  end

  def show
  end

  def new
  	@vehicle = current_user.vehicles.build
  end

  def edit
  end

  def create
  	@vehicle = current_user.vehicles.build(vehicle_params)
  	if current_user.vehicles.count < 2
	  	if @vehicle.save
	  		redirect_to @vehicle
	  	else
	  		render 'new'
	  	end
  	else
  		flash.now[:alert] = 'You can only register two vehicles.'
  		render 'new'
  	end
  end

  def update
  	if @vehicle.update(vehicle_params)
      redirect_to @vehicle
    else
      render 'edit'
    end
  end

  def destroy
  	@vehicle.destroy(params[:id])
    redirect_to @vehicle
  end
  
  private

  def find_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:license, :colour, :make, :model, :year, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vehicleapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	</div>
	<nav class="navbar">
		<ul class="nav navbar-nav">
			<li><%= link_to 'Sign Up', new_user_registration_path, :class => "navLink" %></li>
			<li><%= link_to 'Sign In', new_user_session_path, :class => "navLink" %></li>
			<li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, :class => "navLink" %></li>
			
			<li><%= link_to 'Display Users', users_path, :class => "navLink" %></li>
			<li><%= link_to 'Display Vehicles', vehicles_path, :class => "navLink" %></li>
			
			<li><%= link_to 'Add New Vehicle', new_vehicle_path, :class => "navLink" %></li>
		</ul>
	</nav>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
        <h2>Errors</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>
    <form class="form-horizontal" role="form">
        <div class="form-group">
            <%= f.label :Email, :class=> "control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :email, :class=> "form-control" %><br>
            </div>
        </div>
        <div class="form-group"> 
            <%= f.label :First_Name, :class=> "control-label col-sm-2" %>
            <div class="col-sm-10"> 
            <%= f.text_field :fname, :class=> "form-control" %><br>
            </div>
        </div>
        <div class="form-group"> 
            <%= f.label :Last_Name, :class=> "control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :lname, :class=> "form-control" %><br>
            </div>
        </div>
        <div class="form-group"> 
            <%= f.label :Street_Address, :class=> "control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :street, :class=> "form-control" %><br>
            </div>
        </div>
        <div class="form-group"> 
            <%= f.label :City, :class=> "control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :city, :class=> "form-control" %><br>
            </div>
        </div>
        <div class="form-group"> 
            <%= f.label :Province, :class=> "control-label col-sm-2" %>
            <div class="col-sm-10"> 
                <%= f.select :province, ['Alberta', 'British Columbia', 'Manitoba',
                                 'Newfoundland and Labrador', 'New Brunswick', 'Northwest
                                          Territories', 'Nova Scotia', 'Nunavut', 'Ontario',
                                 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon'], {}, class: "form-control" %><br>
            </div>
        </div>
        <div class="form-group"> 
            <%= f.label :Postal_Code, :class=> "control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :postal, :class=> "form-control", :placeholder=> "A0A 0A0"%><br>
            </div>
        </div>
        <div class="form-group"> 
            <%= f.label :Telephone_Number, :class=> "control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :phone, :class=> "form-control", :placeholder=> "613123567" %><br>
            </div>
        </div>
        <%= f.submit class: "btn btn-primary " %>
    </form>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users List</h1>
<table class="table">
	<thead>
		<tr>
			<th class="text-center">Email</th>
			<th class="text-center">First Name</th>
			<th class="text-center">Last Name</th>
		</tr>
	</thead>
	<tbody>
		<% if current_user.role_id == 1 %>
		<% @users.each do |user| %>
		<tr>
			<td><%= user.email %></td>
			<td><%= user.fname %></td>
			<td><%= user.lname %></td>
			<td><%= link_to 'Show', user %></td>
			<td><%= link_to 'Edit', edit_user_path(user) %></td>
			<td><%= link_to 'Delete', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
		<% end %>
		<% else %>
		<tr>
			<td><%= current_user.email %></td>
			<td><%= current_user.fname %></td>
			<td><%= current_user.lname %></td>
			<td><%= link_to 'Show', current_user %></td>
			<td><%= link_to 'Edit', edit_user_path(current_user) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/show.html.erb
<div class="container-fluid">
<div class="row">
    <label class="control-label col-sm-2">Email</label>
    <div class="col-sm-10 text-left">
        <%= @user.email %><br>
    </div>
</div>
<div class="row">
    <label class="control-label col-sm-2">First Name</label>
    <div class="col-sm-10 text-left"> 
    <%= @user.fname %><br>
    </div>
</div>
<div class="row">
    <label class="control-label col-sm-2">Last Name</label>
    <div class="col-sm-10 text-left">
        <%= @user.lname %><br>
    </div>
</div>
<div class="row"> 
    <label class="control-label col-sm-2">Street Address</label>
    <div class="col-sm-10 text-left">
        <%= @user.street %><br>
    </div>
</div>
<div class="row"> 
    <label class="control-label col-sm-2">City</label>
    <div class="col-sm-10 text-left">
        <%= @user.city %><br>
    </div>
</div>
<div class="row">
    <label class="control-label col-sm-2">Province</label>
    <div class="col-sm-10 text-left"> 
        <%= @user.province %><br>
    </div>
</div>
<div class="row">
    <label class="control-label col-sm-2">Postal Code</label>
    <div class="col-sm-10 text-left">
        <%= @user.postal %><br>
    </div>
</div>
<div class="row"> 
    <label class="control-label col-sm-2">Telephone Number</label>
    <div class="col-sm-10 text-left">
        <%= @user.phone %><br>
    </div>
</div>
</div>

<%= link_to 'Edit User', edit_user_path(@user) %>

<% if current_user.role_id == 1 %>
	<%= link_to 'Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?'} %>
<% end %>

app/views/vehicles/_form.html.erb

    <%= form_for @vehicle do |f| %>
    <% if @vehicle.errors.any? %>
        <h2>Errors</h2>
        <ul>
          <% @vehicle.errors.full_messages.each do |message| %>
            <li class="error"><%= message %></li>
          <% end %>
        </ul>
    <% end %>
    <form class="form-horizontal">
    <div class="form-group">
        <%= f.label :License_Plate, :class=> "control-label col-sm-2" %>
        <div class="col-sm-10">
            <%= f.text_field :license, :class=> "form-control", :placeholder=> "License Plate" %><br>
        </div>
    </div>
    <div class="form-group"> 
        <%= f.label :Colour, :class=> "control-label col-sm-2" %>
        <div class="col-sm-10"> 
            <%= f.text_field :colour, :class=> "form-control" %><br>
        </div>
    </div>
    <div class="form-group"> 
        <%= f.label :Make, :class=> "control-label col-sm-2"  %>
        <div class="col-sm-10"> 
            <%= f.text_field :make, :class=> "form-control" %><br>
        </div>
    </div>
    <div class="form-group"> 
        <%= f.label :Model, :class=> "control-label col-sm-2"  %>
        <div class="col-sm-10"> 
            <%= f.text_field :model, :class=> "form-control" %><br>
        </div>
    </div>
    <div class="form-group"> 
        <%= f.label :Year, :class=> "control-label col-sm-2"  %>
        <div class="col-sm-10">
            <%= f.text_field :year, :class=> "form-control" %><br>
        </div>
    </div>
        <%= f.submit class: "btn btn-primary" %>
    </form>
    <% end %>

app/views/vehicles/edit.html.erb
<h1>Edit Vehicle</h1>

<%= render 'form' %><br><br><br>

<bold>Status: </bold>
<% if @vehicle.status %>
  <strong>Paid</strong>
<% else %>
  <strong id="status">Unpaid</strong><br>
  <%= link_to image_tag('/PayPal.gif'), {action: 'update', controller: 'vehicles'}, {class: 'PayPal'}%>
<% end %>

<br><br><%= link_to 'Show All', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Vehicles List</h1>
<table class="table">
	<thead>
		<tr>
			<th class="text-center">Vehicle</th>
			<th class="text-center">User</th>
		</tr>
	</thead>
	<tbody>
		<% @vehicles.each do |vehicle| %>
		<% if vehicle.user == current_user %>
		<tr>
			<td><%= vehicle.license %></td>
			<td><%= vehicle.user.email %></td>
			<td><%= link_to 'Show', vehicle %></td>
			<td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
			<td><%= link_to 'Delete', vehicle, method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
		<% elsif current_user.role_id == 1 %>
		<tr>
			<td><%= vehicle.license %></td>
			<td><%= vehicle.user.email %></td>
			<td><%= link_to 'Show', vehicle %></td>
			<td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
			<td><%= link_to 'Delete', vehicle, method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
		<% end %>
		<% end %>
	</tbody>
</table>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show All', vehicles_path %>

app/views/vehicles/show.html.erb
<div class="container-fluid">
<div class="row">
    <label class="control-label col-sm-2">License</label>
    <div class="col-sm-10 text-left">
        <%= @vehicle.license %><br>
    </div>
</div>
<div class="row">
    <label class="control-label col-sm-2">User Email</label>
    <div class="col-sm-10 text-left"> 
    <%= @vehicle.user.email %><br>
    </div>
</div>
</div>
<%= link_to 'Edit', edit_vehicle_path(@vehicle) %>

<%= link_to 'Delete', vehicle_path(@vehicle), method: :delete, data: { confirm: 'Are you sure?'} %>